/* Probable Atlas · Economics: "History" tab + "How it works" tab. */
const VH = (() => {
  const { esc, ok, num, pct, sgn } = K;

  /* ---------------- world ---------------- */
  function world() {
    const wS = E.imfS('NGDP_RPCH', 'WEOWORLD', 1980, E.CY + 5);
    const wpc = new Map(E.wbS('NY.GDP.PCAP.KD.ZG', 'WLD', 1970));
    const bars = C.bars({ items: wS.map(([y, v]) => ({ label: String(y), y: v, proj: y >= E.VYEAR, color: ok(wpc.get(y)) && wpc.get(y) < 0 ? 'var(--s2)' : 'var(--s1)' })), h: 240, yFmt: v => num(v, 0) + '%', name: 'World growth', legendItems: [{ name: 'World growth', color: 'var(--s1)', kind: 'sq' }, { name: 'Global recession (output per person fell)', color: 'var(--s2)', kind: 'sq' }, { name: 'IMF projection (faded)', color: 'color-mix(in srgb, var(--s1) 45%, transparent)', kind: 'sq' }], tip: d => `<b>${d.label}</b>${K.tipRow(d.color, d.proj ? 'IMF projection' : 'World growth', pct(d.y, 1))}${ok(wpc.get(+d.label)) ? K.tipRow(null, 'Per person (World Bank)', pct(wpc.get(+d.label), 1)) : ''}`, aria: 'World growth history' });
    // global downturns
    const G = E.COUNTRIES.map(c => c.iso);
    const downs = [...wpc].filter(([, v]) => v < 0).map(([y]) => {
      const gr = G.map(i => E.wb('NY.GDP.MKTP.KD.ZG', i, y)).filter(ok);
      const deep = E.COUNTRIES.filter(c => c.top40).map(c => ({ iso: c.iso, g: E.wb('NY.GDP.MKTP.KD.ZG', c.iso, y) })).filter(x => ok(x.g)).sort((a, b) => a.g - b.g).slice(0, 3);
      return `<tr><td>${y}</td><td>${pct(E.wb('NY.GDP.MKTP.KD.ZG', 'WLD', y), 1)}</td><td>${pct(wpc.get(y), 1)}</td><td>${pct(gr.filter(v => v < 0).length / gr.length * 100, 0)} of ${gr.length}</td><td style="text-align:left">${deep.map(x => `${V.clink(x.iso)} ${pct(x.g, 1)}`).join(', ')}</td></tr>`;
    }).join('');
    // leaders by GDP
    const yrs = [1980, 1990, 2000, 2010, 2020, E.CY, E.CY + 5];
    const top = yrs.map(y => E.COUNTRIES.map(c => ({ iso: c.iso, v: E.imf('NGDPD', c.iso, y) })).filter(x => ok(x.v)).sort((a, b) => b.v - a.v).slice(0, 10));
    const lead = `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Rank</th>${yrs.map(y => `<th>${y}${y > E.VYEAR - 1 ? '*' : ''}</th>`).join('')}</tr></thead><tbody>${Array.from({ length: 10 }, (_, i) => `<tr><td>#${i + 1}</td>${top.map(t => t[i] ? `<td style="text-align:left">${V.clink(t[i].iso)} <span class="muted">${K.big(t[i].v * 1e9, 1, '$')}</span></td>` : '<td>–</td>').join('')}</tr>`).join('')}</tbody></table></div>`;
    // inflation: world + share of economies above 10% (two charts, one scale each)
    const infW = E.imfS('PCPIPCH', 'WEOWORLD', 1980, E.CY + 5);
    const med = [], share = [];
    for (let y = 1980; y <= E.CY + 5; y++) { const a = G.map(i => E.imf('PCPIPCH', i, y)).filter(ok); if (a.length > 50) { med.push([y, S.median(a)]); share.push({ label: String(y), y: a.filter(v => v >= 10).length / a.length * 100, proj: y >= E.VYEAR }); } }
    const infChart = C.line({ series: [{ name: 'World (IMF aggregate)', pts: infW, color: 'var(--s1)', width: 2 }, { name: 'Median economy', pts: med, color: 'var(--s2)', width: 2 }], h: 240, projFrom: E.VYEAR - 0.5, y1: 40, yFmt: v => num(v, 0) + '%', tipX: x => String(Math.round(x)), aria: 'World inflation' });
    const shareChart = C.bars({ items: share, h: 240, yFmt: v => num(v, 0) + '%', color: 'var(--s2)', name: 'Share above 10%', aria: 'Share of economies with double-digit inflation' });
    return V.sec('Half a century of the world economy', 'World growth since 1980 with the four global recessions, the economies that led each decade, and the long retreat and 2022 return of inflation.') +
      V.card('World real GDP growth', 'IMF aggregate at market-weighted PPP. Orange bars are years when world output per person fell (World Bank), the usual definition of a global recession.', bars) +
      `<div class="grid g2" style="margin-top:14px">${V.card('Global recessions', 'Years when world GDP per person fell, from World Bank data back to 1970.', `<div class="tbl-wrap"><table class="tbl"><thead><tr><th>Year</th><th>World growth</th><th>Per person</th><th>Economies shrinking</th><th style="text-align:left">Deepest among the top 40</th></tr></thead><tbody>${downs}</tbody></table></div>`)}${V.card('Inflation around the world', 'The IMF world figure is pulled up by a few very high-inflation economies; the median economy is the better gauge of the typical experience.', infChart)}</div>` +
      `<div class="grid g2" style="margin-top:14px">${V.card('Economies with double-digit inflation', 'Share of economies with inflation of 10% or more each year.', shareChart)}${V.card('The ten largest economies', 'GDP in current US dollars. * IMF estimate or projection.', lead)}</div>`;
  }

  /* ---------------- United States ---------------- */
  function us() {
    const recs = E.recessionList().filter(r => r.start >= 1948 * 12);
    const G = E.qSeries('GDPC1'), U = E.mSeries('UNRATE'), rec = M.recession(), cm = rec.models.classic;
    const rows = recs.map(r => {
      const q0 = Math.floor(r.start / 3), q1 = Math.floor(r.end / 3);
      let peak = null; for (let q = q0 - 2; q <= q0; q++) { const v = E.qAt(G, q); if (ok(v) && (peak == null || v > peak)) peak = v; }
      let trough = null; for (let q = q0; q <= q1 + 1; q++) { const v = E.qAt(G, q); if (ok(v) && (trough == null || v < trough)) trough = v; }
      const u0 = E.mAt(U, r.start - 1); let uMax = null; for (let t = r.start; t <= r.end + 18; t++) { const v = E.mAt(U, t); if (ok(v) && (uMax == null || v > uMax)) uMax = v; }
      let minSp = null, maxP = null; for (let t = r.start - 24; t <= r.start - 1; t++) { const s = rec.spread(t); if (ok(s)) { minSp = minSp == null ? s : Math.min(minSp, s); const p = cm.fit.prob([s]); maxP = maxP == null ? p : Math.max(maxP, p); } }
      return { name: `${K.mLab(r.start)} – ${K.mLab(r.end)}`, start: r.start, months: r.end - r.start + 1, gdp: ok(peak) && ok(trough) ? (trough / peak - 1) * 100 : null, unemp: ok(u0) && ok(uMax) ? uMax - u0 : null, inv: ok(minSp) ? (minSp < 0 ? 'Yes' : 'No') : '–', minSp, maxP: ok(maxP) ? maxP * 100 : null };
    });
    const recTbl = T.html({ cols: [{ k: 'name', lab: 'Recession', sortVal: r => r.start }, { k: 'months', lab: 'Months', num: true, good: -1, d: 0, fmt: v => String(v) }, { k: 'gdp', lab: 'GDP peak to trough', num: true, good: 1, fmt: v => pct(v, 1) }, { k: 'unemp', lab: 'Jobless rate rise', num: true, good: -1, fmt: v => ok(v) ? sgn(v, 1) + ' pp' : '–' }, { k: 'inv', lab: 'Curve inverted before?', title: '10-year minus 3-month spread below zero in the 24 months before the start' }, { k: 'maxP', lab: 'Peak model odds before', num: true, good: 1, fmt: v => pct(v, 0), title: 'Highest yield-curve model probability in the 24 months before the start (fit on all data)' }], rows, sort: { k: 'name', dir: -1 }, search: false, limit: 20, views: ['table', 'heat'] });
    const eras = C.line({ series: [{ name: 'Fed funds rate', pts: E.mPts(E.mSeries('FEDFUNDS'), 1955 * 12), color: 'var(--s1)', width: 1.6 }, { name: 'CPI inflation', pts: E.mPts(E.mYoY(E.mSeries('CPIAUCSL')), 1955 * 12), color: 'var(--s2)', width: 1.6 }, { name: 'Unemployment', pts: E.mPts(U, 1955 * 12), color: 'var(--s3)', width: 1.6 }], shade: E.recessions(), shadeName: 'Recession', h: 300, endLabels: true, yFmt: v => num(v, 0) + '%', tipX: x => K.mLab(Math.round(x * 12)), vlines: [{ x: 1979.6, label: 'Volcker' }, { x: 2008.9, label: 'Zero rates' }, { x: 2022.2, label: '2022 hikes' }], aria: 'US eras' });
    // decades
    const GR = E.qSeries('A191RL1Q225SBEA'), CPI = E.mYoY(E.mSeries('CPIAUCSL')), FF = E.mSeries('FEDFUNDS'), GS = E.mSeries('GS10');
    const mAvg = (ms, a, b) => { const v = []; for (let t = a * 12; t < b * 12; t++) { const x = E.mAt(ms, t); if (ok(x)) v.push(x); } return v.length > 12 ? S.mean(v) : null; };
    const qAvg = (qs, a, b) => { const v = []; for (let q = a * 4; q < b * 4; q++) { const x = E.qAt(qs, q); if (ok(x)) v.push(x); } return v.length > 4 ? S.mean(v) : null; };
    const dec = []; for (let d = 1950; d <= 2020; d += 10) dec.push({ name: d + 's', g: qAvg(GR, d, d + 10), inf: mAvg(CPI, d, d + 10), u: mAvg(U, d, d + 10), ff: mAvg(FF, d, d + 10), y10: mAvg(GS, d, d + 10), n: recs.filter(r => r.start >= d * 12 && r.start < (d + 10) * 12).length });
    const decTbl = T.html({ cols: [{ k: 'name', lab: 'Decade' }, { k: 'g', lab: 'GDP growth', num: true, good: 1, fmt: v => pct(v, 1) }, { k: 'inf', lab: 'Inflation', num: true, good: -1, fmt: v => pct(v, 1) }, { k: 'u', lab: 'Unemployment', num: true, good: -1, fmt: v => pct(v, 1) }, { k: 'ff', lab: 'Fed funds', num: true, good: 0, fmt: v => pct(v, 1) }, { k: 'y10', lab: '10-year yield', num: true, good: 0, fmt: v => pct(v, 1) }, { k: 'n', lab: 'Recessions', num: true, good: -1, fmt: v => String(v) }], rows: dec, sort: { k: 'name', dir: 1 }, search: false, views: ['table', 'heat', 'chart'], view: 'heat', limit: 10 });
    // records
    const maxOf = (ms, from = 0) => { let b = null; ms.v.forEach((v, i) => { const t = ms.t0 + i; if (t >= from && ok(v) && (!b || v > b.v)) b = { t, v }; }); return b; };
    const minOf = (ms, from = 0) => { let b = null; ms.v.forEach((v, i) => { const t = ms.t0 + i; if (t >= from && ok(v) && (!b || v < b.v)) b = { t, v }; }); return b; };
    const hi = maxOf(CPI, 1948 * 12), uHi = maxOf(U), uLo = minOf(U, 1970 * 12), ffHi = maxOf(FF);
    let qMin = null, qMax = null; GR.v.forEach((v, i) => { if (!ok(v)) return; const q = GR.q0 + i; if (!qMin || v < qMin.v) qMin = { q, v }; if (!qMax || v > qMax.v) qMax = { q, v }; });
    let longest = { m: 0 }; for (let i = 1; i < recs.length; i++) { const m = recs[i].start - recs[i - 1].end - 1; if (m > longest.m) longest = { m, a: recs[i - 1].end + 1, b: recs[i].start - 1 }; }
    const last = recs[recs.length - 1], sinceLast = (E.mLast(U) - last.end);
    const tiles = [V.tile({ lab: 'Highest inflation since 1948', val: pct(hi.v, 1), sub: K.mLab(hi.t) }), V.tile({ lab: 'Highest unemployment', val: pct(uHi.v, 1), sub: K.mLab(uHi.t) }), V.tile({ lab: 'Lowest unemployment since 1970', val: pct(uLo.v, 1), sub: K.mLab(uLo.t) }), V.tile({ lab: 'Highest fed funds rate', val: pct(ffHi.v, 1), sub: K.mLab(ffHi.t) }), V.tile({ lab: 'Worst quarter for GDP', val: pct(qMin.v, 1), sub: K.qLab(qMin.q) + ' (annualized)' }), V.tile({ lab: 'Best quarter for GDP', val: pct(qMax.v, 1), sub: K.qLab(qMax.q) + ' (annualized)' }), V.tile({ lab: 'Longest expansion', val: String(longest.m), unit: 'months', sub: `${K.mLab(longest.a)} – ${K.mLab(longest.b)}` }), V.tile({ lab: 'Current expansion so far', val: String(sinceLast), unit: 'months', sub: `Since ${K.mLab(last.end + 1)}` })].join('');
    return V.sec('US economic history', `${recs.length} recessions since 1948, the eras of inflation and interest rates, decade averages and records.`) +
      `<div class="tiles t4">${tiles}</div>` + `<div style="margin-top:14px">${V.card('Rates, inflation and jobs since 1955', 'Shaded bands are NBER recessions.', eras)}</div>` +
      V.sec('Every recession since 1948', 'Depth, the jobs hit, and whether the yield curve gave warning. Sort any column; switch to Heat map to compare.') + recTbl +
      V.sec('Decade by decade', 'Averages of quarterly GDP growth and monthly data; heat map colors show better (blue) and worse (red) decades.') + decTbl;
  }

  /* ---------------- single country ---------------- */
  function country(iso) {
    const gS = E.imfS('NGDP_RPCH', iso, 1980, E.CY + 5), iS = E.imfS('PCPIPCH', iso, 1980, E.CY + 5);
    if (!gS.length) return V.card('History', '', '<div class="empty">No IMF history for this economy.</div>');
    const bars = C.bars({ items: gS.map(([y, v]) => ({ label: String(y), y: v, proj: y >= E.VYEAR, color: v < 0 ? 'var(--s2)' : 'var(--s1)' })), h: 240, yFmt: v => num(v, 0) + '%', name: 'Growth', legendItems: [{ name: 'Growth', color: 'var(--s1)', kind: 'sq' }, { name: 'Contraction', color: 'var(--s2)', kind: 'sq' }], aria: 'Growth history' });
    const hiInf = iS.some(p => p[1] > 40);
    const infC = C.line({ series: [{ name: 'Inflation', pts: iS.map(([y, v]) => [y, hiInf ? Math.sign(v) * Math.log10(1 + Math.abs(v)) : v]), color: 'var(--s2)', width: 2 }], h: 220, projFrom: E.VYEAR - 0.5, yFmt: hiInf ? (v => num(Math.sign(v) * (Math.pow(10, Math.abs(v)) - 1), 0) + '%') : (v => num(v, 0) + '%'), tipFmt: hiInf ? (v => num(Math.sign(v) * (Math.pow(10, Math.abs(v)) - 1), 1) + '%') : (v => num(v, 1) + '%'), tipX: x => String(Math.round(x)), aria: 'Inflation history' });
    const act = gS.filter(p => p[0] < E.VYEAR), best = act.reduce((a, b) => b[1] > a[1] ? b : a), worst = act.reduce((a, b) => b[1] < a[1] ? b : a);
    const iAct = iS.filter(p => p[0] < E.VYEAR), iHi = iAct.length ? iAct.reduce((a, b) => b[1] > a[1] ? b : a) : null;
    const uS = E.imfS('LUR', iso, 1980, E.VYEAR - 1), uHi = uS.length ? uS.reduce((a, b) => b[1] > a[1] ? b : a) : null;
    const dS = E.imfS('GGXWDG_NGDP', iso, 1980, E.CY + 5), dHi = dS.length ? dS.reduce((a, b) => b[1] > a[1] ? b : a) : null;
    const crises = act.filter(p => p[1] <= -2).map(p => p[0]);
    const rankIn = y => { const all = E.COUNTRIES.map(c => ({ iso: c.iso, v: E.imf('NGDPD', c.iso, y) })).filter(x => ok(x.v)).sort((a, b) => b.v - a.v); const i = all.findIndex(x => x.iso === iso); return i >= 0 ? i + 1 : null; };
    const yrs = [1980, 1990, 2000, 2010, 2020, E.CY, E.CY + 5];
    const tiles = [V.tile({ lab: 'Best year', val: pct(best[1], 1), sub: String(best[0]) }), V.tile({ lab: 'Worst year', val: pct(worst[1], 1), sub: String(worst[0]) }), iHi ? V.tile({ lab: 'Peak inflation', val: pct(iHi[1], iHi[1] > 100 ? 0 : 1), sub: String(iHi[0]) }) : '', uHi ? V.tile({ lab: 'Peak unemployment', val: pct(uHi[1], 1), sub: String(uHi[0]) }) : '', dHi ? V.tile({ lab: 'Peak government debt', val: pct(dHi[1], 0), unit: 'of GDP', sub: String(dHi[0]) + (dHi[0] >= E.VYEAR ? ' (projected)' : '') }) : '', V.tile({ lab: 'Years of contraction since 1980', val: String(act.filter(p => p[1] < 0).length), unit: `of ${act.length}`, sub: crises.length ? 'Deep (≤ −2%): ' + crises.join(', ') : 'No year below −2%' })].join('');
    const dec = []; for (let d = 1980; d <= 2020; d += 10) { const a = d, b = Math.min(d + 9, E.VYEAR - 1); dec.push({ name: d + 's', g: E.avg('imf', 'NGDP_RPCH', iso, a, b), inf: E.avg('imf', 'PCPIPCH', iso, a, b), u: E.avg('imf', 'LUR', iso, a, b), debt: E.avg('imf', 'GGXWDG_NGDP', iso, a, b), ca: E.avg('imf', 'BCA_NGDPD', iso, a, b) }); }
    const decTbl = T.html({ cols: [{ k: 'name', lab: 'Decade' }, { k: 'g', lab: 'Growth', num: true, good: 1, fmt: v => pct(v, 1) }, { k: 'inf', lab: 'Inflation', num: true, good: -1, fmt: v => pct(v, 1) }, { k: 'u', lab: 'Unemployment', num: true, good: -1, fmt: v => pct(v, 1) }, { k: 'debt', lab: 'Gov. debt', num: true, good: -1, fmt: v => pct(v, 0) }, { k: 'ca', lab: 'Current account', num: true, good: 0, fmt: v => ok(v) ? sgn(v, 1) + '%' : '–' }], rows: dec, sort: { k: 'name', dir: 1 }, search: false, views: ['table', 'heat'], view: 'heat', limit: 10 });
    const rk = `<div class="tbl-wrap"><table class="tbl"><thead><tr>${yrs.map(y => `<th>${y}${y > E.VYEAR - 1 ? '*' : ''}</th>`).join('')}</tr></thead><tbody><tr>${yrs.map(y => { const r = rankIn(y); return `<td>${r ? '#' + r : '–'}</td>`; }).join('')}</tr></tbody></table></div>`;
    return V.sec(`${E.name(iso)}: history`, 'IMF data since 1980, with projections faded.') + `<div class="tiles">${tiles}</div>` +
      `<div class="grid g2" style="margin-top:14px">${V.card('Real GDP growth', 'Orange bars are contractions; faded bars are IMF projections.', bars)}${V.card('Inflation', hiInf ? 'Log scale: this economy has had inflation above 40%.' : 'Consumer prices, yearly average.', infC)}</div>` +
      `<div class="grid g-7-5" style="margin-top:14px">${V.card('Decade averages', 'Heat map colors compare the decades with each other.', decTbl)}${V.card('World rank by GDP', 'Rank among economies with IMF data, in current US dollars. * estimate or projection.', rk)}</div>`;
  }
  function view(st) { return st.scope === 'WLD' ? world() : st.scope === 'USA' ? us() + country('USA') : country(st.scope); }

  /* ---------------- How it works ---------------- */
  function how() {
    const rec = M.recession(), n = M.nowcast(), inf = M.inflation(), g = M.growth(), lv = M.levers();
    const st = E.ST || {};
    const srcRow = (name, url, what) => `<li><a href="${url}" target="_blank" rel="noopener">${name}</a>: ${what}</li>`;
    return V.sec('How it works', 'Sources, the refresh pipeline, every model in plain language, how accurate each one has been, and the limits.') +
      `<div class="grid g-7-5"><div class="prose">
      <h3>Sources</h3><ul>
      ${srcRow('World Bank World Development Indicators', 'https://data.worldbank.org/', '36 indicators for every economy from 1970 (growth, prices, jobs, trade, investment, structure, people).')}
      ${srcRow('World Bank Worldwide Governance Indicators', 'https://www.worldbank.org/en/publication/worldwide-governance-indicators', 'government effectiveness, rule of law, control of corruption, regulatory quality, stability, voice.')}
      ${srcRow('IMF World Economic Outlook (DataMapper)', 'https://www.imf.org/external/datamapper/', `${esc(E.VINT)}: history from 1980 and projections to ${E.CY + 5}.`)}
      ${srcRow('FRED, Federal Reserve Bank of St. Louis', 'https://fred.stlouisfed.org/', '52 US series (BEA, BLS, Federal Reserve, Treasury, CBO, University of Michigan, Chicago and Atlanta Feds) and NBER recession dates.')}
      </ul>
      <h3>Refresh</h3><p>A scheduled GitHub Actions job in the portfolio repository pulls every source twice a day (weekday mornings after the 8:30 ET releases, and every evening), keeps the last good copy of any series that fails, and publishes the result with the site. The IMF updates its outlook in April and October; the World Bank updates through the year. Last run: ${esc(K.isoLab((st.fetched_at || '').slice(0, 10)))}, with ${Object.entries(st.sources || {}).map(([k, v]) => `${esc(k)} ${esc(v)}`).join(', ')} series loaded.</p>
      <h3>Recession probability</h3><p>A probit model: P(recession in 12 months) = Φ(a + b × spread), where the spread is the 10-year minus 3-month Treasury yield, estimated on ${rec.models.classic.fit.n} months since 1959. The second model adds the real fed funds rate and the Chicago Fed's financial conditions index. Out of sample since 1985 the yield-curve model scores an AUC of ${num(rec.models.classic.score.auc, 2)} (1 is perfect, 0.5 is a coin flip) and flagged each of the last ${rec.models.classic.score.recs.length} recessions in advance, with ${rec.models.classic.score.falseAlarms} false alarms.</p>
      <div class="formula">P(recession at t+12) = Φ(${num(rec.models.classic.fit.b[0], 2)} ${rec.models.classic.fit.b[1] < 0 ? '−' : '+'} ${num(Math.abs(rec.models.classic.fit.b[1]), 2)} × spread_t)</div>
      <h3>GDP nowcast</h3><p>A bridge equation: quarterly GDP growth regressed on the quarter's growth in payrolls, industrial production, real retail sales, real income excluding transfers, housing starts and jobless claims (1992 to today, pandemic quarters excluded, robust errors). Months not yet published are filled with each series' short-run trend. Backtest error since 2005: ${num(n.score.rmse, 2)} pp vs ${num(n.score.naive, 2)} pp for a naive average; the Atlanta Fed's GDPNow (${num(n.score.gdpnowRmse, 2)} pp) is shown as the benchmark.</p>
      <h3>Inflation forecast</h3><p>Twelve direct regressions, one per horizon, of future 12-month CPI inflation on today's inflation, six-month core momentum, household inflation expectations, the unemployment gap (versus CBO's natural rate) and the 12-month change in oil prices, estimated since 1987. The 80% band comes from each horizon's residual spread. The 12-month forecast error since 2001 is ${num(inf.score.rmse, 2)} pp, vs ${num(inf.score.rw, 2)} pp for "inflation stays where it is".</p>
      <h3>Country growth and contraction risk</h3><p>Each economy's growth reverts toward its 20-year median at a pooled rate of ${num(g.rho, 2)} a year. The chance of a contraction centers on the IMF forecast, with a spread equal to how far that economy's growth has typically landed from forecast (median absolute error × 1.48). Growth fans come from 2,000 simulated paths with persistent, fat-tailed shocks. Backtest since 2000: ${num(g.score.rmse, 2)} pp error vs ${num(g.score.naive, 2)} pp for "same as last year".</p>
      <h3>Archetypes and anomalies</h3><p>Seven fundamentals are clipped to the 4th–96th percentile, standardized and grouped with k-means (k = 5, 16 random restarts). Principal components give the two chart axes. Anomalies compare this year's IMF figure with the economy's previous ten years (pandemic years excluded) as a z-score.</p>
      <h3>Growth levers and recommendations</h3><p>A panel of ${lv.n} country-decades (1996–2005, 2006–15, 2016–${E.VYEAR - 1}) regresses average growth per person on starting income, population growth, investment, size-adjusted trade openness, government effectiveness, inflation, women's participation and starting debt, with decade effects and robust standard errors (R² ${num(lv.fit.r2, 2)}). Recommendations use only levers with p < 0.10 and the expected sign, set a realistic target (the income-group median, or the best quartile once a country is above the median), and report the associated gain with a 90% range. Fiscal recommendations use debt arithmetic: debt(t+1) = debt(t) × (1 + i) ÷ (1 + nominal growth) − primary balance, calibrated to the IMF path.</p>
      <h3>Limits</h3><ul><li>Cross-country regressions show associations, not causes; confidence levels are capped at Medium for that reason.</li><li>Backtests use today's revised data, which makes every model look better than it would have in real time.</li><li>NBER dates recessions after the fact; the IMF revises its projections twice a year; small economies have noisier data.</li><li>This is an analytical and educational tool, not investment, legal or policy advice.</li></ul>
      </div>
      <div class="grid" style="align-content:start">${V.card('Glossary', '', `<dl class="kv" style="grid-template-columns:auto minmax(0,1fr);text-align:left">${[['pp', 'percentage points: the difference between two percentages'], ['SAAR', 'seasonally adjusted annual rate'], ['PPP', 'purchasing power parity: adjusts for price levels across countries'], ['Probit', 'a model that turns a signal into a probability'], ['AUC', 'how well a model ranks months with and without a recession (0.5 = random)'], ['Brier score', 'average squared error of probability forecasts (lower is better)'], ['RMSE', 'root mean squared error of forecasts'], ['r − g', 'interest rate on debt minus nominal growth; positive makes debt harder to stabilize'], ['Primary balance', 'budget balance excluding interest payments'], ['Taylor rule', 'a benchmark policy rate from inflation and the output gap'], ['Output gap', 'actual GDP versus potential (CBO), in percent'], ['Sahm rule', 'a recession signal when the 3-month average jobless rate rises 0.5 pp above its 12-month low']].map(([a, b]) => `<dt><b>${a}</b></dt><dd style="text-align:left;font-family:var(--f-sans)">${b}</dd>`).join('')}</dl>`)}
      ${V.card('Part of Probable Atlas', '', `<div class="prose" style="font-size:13.5px"><p>Probable Atlas extends the <a href="https://bsilva87921.github.io/live-sports-lab/" target="_blank" rel="noopener">Probable Sports Lab</a> approach to world domains: live data, predictive models, a what-if lab and evidence-based recommendations. Economics is module 1; finance and markets, commodities and scarcity, weather, agriculture, hunger, wealth, technology and conflict follow on the same shared kit.</p><p>Built by Bruno Silva.</p></div>`)}</div></div>`;
  }
  return { view, how };
})();
